### ISSUE TITLE
Figures url broken?

### ISSUE THREAD

**Issue by tianqig** [WhoIsJack/python-workshop-image-processing#1]
Somehow I could not see any Figures in the notebook at

 https://github.com/WhoIsJack/python-workshop-image-processing/blob/master/main_tutorial/tutorial_pipeline.ipynb

Are the URLs broken? 

Thanks

**Comment by WhoIsJack** [comment]
Works fine for me.

Bear in mind that these are not URLs pointing to an online source but local paths pointing to the `ipynb_images` directory, which is expected to be in the same folder as the notebook itself.

Thus, it should work when the nb is viewed locally from a clone of the repo but it doesn't work in GitHub's browser rendering, which doesn't track local paths.

Let me know if this was the problem.

**Comment by tianqig** [comment]
Thanks for your quick reply, you are right that it worked for a local copy
